FROM quay.io/keycloak/keycloak:23.0.1

# Set environment variables
# ENV KEYCLOAK_ADMIN=admin
# ENV KEYCLOAK_ADMIN_PASSWORD=admin
# ENV KC_PROXY=edge

# Expose Keycloak ports
EXPOSE 8080

# # Start Keycloak with custom arguments
 CMD ["start-dev"]